### ISSUE TITLE
Questions and a error in the readme

### ISSUE THREAD

**Issue by Rotoslider** [hku-mars/LiDAR_IMU_Init#10]
I now have the Livox Horizon working with your package. Very nice so far.  Next up the Velodyne when I get some time in a few days. I have a couple questions in the mean time. 
Are there any plans to add loop closure to the package like scan context? 
Have you tried rotating your lidar unit so that it is 90 degrees to ground with Y up for example and then spinning your lidar unit and imu around in the axis? It would be similar to how the Geoslam, Kaarta and Green valley scanners work. It seems one could get a very good scan this way. Lots of data and continuous motion in the rotation axis. 

There may be an error in the readme for startup of launch file. Seems you call roslaunch twice in one line. 

cd catkin_ws
source devel/setup.bash
**_roslaunch lidar_imu_init_** roslaunch lidar_imu_init xxx.launch

**Comment by zfc-zfc** [comment]
> I now have the Livox Horizon working with your package. Very nice so far. Next up the Velodyne when I get some time in a few days. I have a couple questions in the mean time. Are there any plans to add loop closure to the package like scan context? Have you tried rotating your lidar unit so that it is 90 degrees to ground with Y up for example and then spinning your lidar unit and imu around in the axis? It would be similar to how the Geoslam, Kaarta and Green valley scanners work. It seems one could get a very good scan this way. Lots of data and continuous motion in the rotation axis.
> 
> There may be an error in the readme for startup of launch file. Seems you call roslaunch twice in one line.
> 
> cd catkin_ws source devel/setup.bash **_roslaunch lidar_imu_init_** roslaunch lidar_imu_init xxx.launch

Hi, thank you for your correction for README.txt. The motivation and aim of this package are to offer initial extrinsic transformation and temporal offset between LiDAR and IMU, so that FAST-LIO2 can run on any device setup. 
As for loop closure algorithms, you can notice the YouTube channel of our lab (https://www.youtube.com/channel/UC_sj0oCXnrBzl2QDn3G38Ww).
