### ISSUE TITLE
在MID-360使用单独激光里程计时直接飞

### ISSUE THREAD

**Issue by af-doom** [hku-mars/LiDAR_IMU_Init#100]
您好，以下是两个数据, 运动很平稳也会飞，很奇怪
 1.https://1drv.ms/u/c/be458a745a2235e4/EfaQK--VySdLjUzORxyi75QBl38c9z27gyhcdaMcyANnkw?e=bnXxpY
2.https://1drv.ms/u/c/be458a745a2235e4/EbEP13-n_apOg6g8eCvs7McBrL0A8c_ivkdTOhuarkDatg?e=lS4SY6

**Comment by zfc-zfc** [comment]
> 您好，以下是两个数据, 运动很平稳也会飞，很奇怪 1.https://1drv.ms/u/c/be458a745a2235e4/EfaQK--VySdLjUzORxyi75QBl38c9z27gyhcdaMcyANnkw?e=bnXxpY 2.https://1drv.ms/u/c/be458a745a2235e4/EbEP13-n_apOg6g8eCvs7McBrL0A8c_ivkdTOhuarkDatg?e=lS4SY6

你的数据原始频率是50Hz。现在的代码默认支持10Hz输入，然后会分帧成50Hz点云。你在driver里改成10Hz就没事了
