### ISSUE TITLE
Point-Lio使用外部雷达是否可以用改方法校准，校准产生的数值是否可以直接

### ISSUE THREAD

**Issue by zbcUN** [hku-mars/LiDAR_IMU_Init#101]
Point-Lio使用外部imu是否可以用改方法校准，校准产生的数值是否可以直接添加在config文件里面？添加后是以雷达坐标系为基准还是以imu坐标系为基准呢？非常感谢您开源的代码他对我非常有帮助，希望您在有时间时候能回答下我的疑问。

**Comment by zfc-zfc** [comment]
> Point-Lio使用外部imu是否可以用改方法校准，校准产生的数值是否可以直接添加在config文件里面？添加后是以雷达坐标系为基准还是以imu坐标系为基准呢？非常感谢您开源的代码他对我非常有帮助，希望您在有时间时候能回答下我的疑问。

可以的。用该方法标定得到的外参可以直接填入Point-LIO的config。LI-Init所得到的外参结果是雷达在IMU坐标系下的位姿，即以IMU为基准。
