### ISSUE TITLE
/usr/bin/ld: 找不到 -lCUDA::cublas /usr/bin/ld: 找不到 -lCUDA::cudart /usr/bin/ld: 找不到 -lCUDA::cusolver /usr/bin/ld: 找不到 -lCUDA::cusparse

### ISSUE THREAD

**Issue by bingquanLi** [hku-mars/LiDAR_IMU_Init#107]
![2024-07-06 00-42-23 的屏幕截图](https://github.com/hku-mars/LiDAR_IMU_Init/assets/144792439/c700b3a5-c6b4-47ee-b330-86988546ea85)

**Comment by Anutlet** [comment]
你好，我遇到了同样的问题，请教下你是如何解决的呢，非常感谢！
