### ISSUE TITLE
Wheel Robot

### ISSUE THREAD

**Issue by h-rover** [hku-mars/LiDAR_IMU_Init#11]
Hi,

Thanks for this great work. I was wondering would this initialization method work on a wheeled robot where the sensors are already mounted? We can only do the Z-axis excitation by rotating the robot on Z. X and Y axes rotations are not possible. Thanks!

**Comment by zfc-zfc** [comment]
> Hi,
> 
> Thanks for this great work. I was wondering would this initialization method work on a wheeled robot where the sensors are already mounted? We can only do the Z-axis excitation by rotating the robot on Z. X and Y axes rotations are not possible. Thanks!

Hi, the current version of LI-Init is not applicable for wheel robots. Maybe you could try OA-LICalib: https://github.com/APRIL-ZJU/OA-LICalib, which might be helpful for wheel robots.
