### ISSUE TITLE
test bags naming clarification

### ISSUE THREAD

**Issue by 85256638** [hku-mars/LiDAR_IMU_Init#112]
Thanks for publishing this great project.

I was wondering whether you could shed some light on the meanings of your test bags names:

1. avia_500ms_indoor.bag
2. avia_50ms_indoor.bag

what does the 500ms and 50ms mean in here?
Thanks in advance!

**Comment by zfc-zfc** [comment]
> Thanks for publishing this great project.
> 
> I was wondering whether you could shed some light on the meanings of your test bags names:
> 
> 1. avia_500ms_indoor.bag
> 2. avia_50ms_indoor.bag
> 
> what does the 500ms and 50ms mean in here? Thanks in advance!

It means the ground-truth of the time lag between Lidar and IMU.
