### ISSUE TITLE
States.h 头文件无法找到

### ISSUE THREAD

**Issue by MagicShawn** [hku-mars/LiDAR_IMU_Init#115]
LiDAR_IMU_Init/src/IMU_Processing.hpp:27:10: fatal error: lidar_imu_init/States.h: No such file or directory
 #include <lidar_imu_init/States.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by blue-stone-j** [comment]
This header file id generated from a .msg file, which locates at packge_folder/msg/States.h . In common cases, this header will be generated during compilation.

**Comment by zfc-zfc** [comment]
> LiDAR_IMU_Init/src/IMU_Processing.hpp:27:10: fatal error: lidar_imu_init/States.h: No such file or directory #include <lidar_imu_init/States.h> ^~~~~~~~~~~~~~~~~~~~~~~~~

编译时使用catkin_make -j1，会先生成States.h文件，再编译主程序。一次不行就多编译几次

**Comment by MagicShawn** [comment]
> > LiDAR_IMU_Init/src/IMU_Processing.hpp：27：10：致命错误：lidar_imu_init/States.h：没有这样的文件或目录 #include <lidar_imu_init/States.h> ^~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 编译时使用catkin_make -j1，会先生成States.h文件，再编译主程序。一次不行就多编译几次

非常感谢！
