### ISSUE TITLE
what's the meaning of "imu_en" in avia.yaml ?

### ISSUE THREAD

**Issue by InterKnight** [hku-mars/LiDAR_IMU_Init#13]
Hi, thank you guys for great project
I'm wondering what's the meaning of "imu_en" in avia.yaml ?
what happen when "imu_en" is true?

**Comment by zfc-zfc** [comment]
> Hi, thank you guys for great project I'm wondering what's the meaning of "imu_en" in avia.yaml ? what happen when "imu_en" is true?

Hi, imu_en is an old parameter, which should be removed. 
When using LI-Init, imu_en should be false.
