### ISSUE TITLE
Tips for improving result accuracy

### ISSUE THREAD

**Issue by Mastergalen** [hku-mars/LiDAR_IMU_Init#15]
Hi there,

Thank you for releasing this great tool for calibration. 

I was able to record a calibration sequence and run it through the application with not much trouble.

Here are the results I got, however, the extrinsics deviate by about 6mm in the x-translation (forward/backward) from what we would expect from our CAD model. 

Are there any tips or gotchas when recording the calibration sequence? I have also also attached the rosbag and the config file we used. [Dropbox Link](https://www.dropbox.com/s/464gybo443938qv/github_issue_livox_mid70.zip?dl=0)

Thank you in advance.

![image](https://user-images.githubusercontent.com/1261152/181837861-92efa22f-1073-447c-a8b7-71439da7c4c5.png)

**Comment by zfc-zfc** [comment]
Hi, thank you for your comments. I want to ask what is the expected translational extrinsic value from your CAD model? If the error is less than 1 or 2 centimeters, I think that would be an acceptable result.
