### ISSUE TITLE
Is it possible to disable the time / temporal calibration?

### ISSUE THREAD

**Issue by seajayshore** [hku-mars/LiDAR_IMU_Init#18]
We are using a hardware syncronised Lidar & IMU setup. I'd like to use this tool to estimate extrinsic rotation & translation but assume that time syncronisation is accurate.

Is there an easy way to disable the time sync estimation in the initialisation stage?

**Comment by zfc-zfc** [comment]
> sync

It needs to modify some codes. I will implement this later. If you are interested, you can try to modify the code in LI_Init.cpp.
