### ISSUE TITLE
What is the 360 LiDAR used?

### ISSUE THREAD

**Issue by seajayshore** [hku-mars/LiDAR_IMU_Init#2]
What is the Mid-360 LiDAR you use?? Is there some link to this or is it pre-release from Livox?

Can you share any links or spec. such as max range and point density?

**Comment by zfc-zfc** [comment]
Mid-360 is a new LiDAR from Livox-Tech. Since it is not offcially released yet, here is only an unofficial introduction of this LIDAR https://view.inews.qq.com/a/20210903V07GSH00. The official release of Mid-360 might come next month.
