### ISSUE TITLE
"No IMU, use constant velocity model."

### ISSUE THREAD

**Issue by ManChrys** [hku-mars/LiDAR_IMU_Init#22]
Hello,

i've tried the package but when i run it the screen is black
![riz](https://user-images.githubusercontent.com/67521662/186671689-84a7fbf4-87fd-4d01-97e6-8137d14c3a36.png)

and on cmd windows says "No IMU, use constant velocity model."
![Screenshot from 2022-08-25 15-14-27](https://user-images.githubusercontent.com/67521662/186670985-1ab78a03-630b-4033-9294-4a65c08661cd.png)

I tested every unit individual (livox mid 40 and xsens mti g 710 gnss/ins) throught their softwares and ros drivers and they are working properly.

in my yaml i just changed the imu topic as you can see below.

![yaml](https://user-images.githubusercontent.com/67521662/186671369-5edb3cab-fc7f-48c1-b75e-72ca4ebc46f6.png)

Edit1;

when i run the livox_avia.launch file it shouldnt start recording from lidar? cause when i rostopic echo /livox/lidar i dont have measurements. Further more if i try to run livox_ros_driver it closed automatically when i run the livox_avia.launch file, brcause its the same node. I run xsens_mti_ros_driver and i have measurements on rostopic echo /imu/data but on LI_Init cmd window says "No IMU, use constant velocity model."

Thanks in advance.

**Comment by zfc-zfc** [comment]
> as

The screen is black because li_init does not subscribe lidar or imu topic.
Please use rostopic echo xxx to make sure the correct topic is published. If there is nothing when you rostopic echo /livox/lidar, it seems the livox_ros_driver does not work properly. 
By the way, what does this mean "Further more if i try to run livox_ros_driver it closed automatically when i run the livox_avia.launch file, **because its the same node**"?

**Comment by ManChrys** [comment]
Hello @zfc-zfc and thanks for the fast answer again!!

When i use livox mid 40 and run the `roslaunch livox_ros_driver livox_lidar.launch` it is working properly. I use `rostopic echo /livox/lidar ` and i am seeing the measurements.

When i use xsens mti-g-710 gnss/ins (imu) and run the `roslaunch xsens_mti_driver example.launch` command imu is working properly i have all meauserments (angular, acc etc), i saw them using the `rostopic echo /imu/data` 


![1](https://user-images.githubusercontent.com/67521662/186701772-7aca1444-f09b-4ecf-a6d8-0f7269f121a1.png)

When i try to run lil_init project i have the problems that i mention above :/

Am i missing something ? :/

Thanks in advance.

**Comment by zfc-zfc** [comment]
> above

So you said, when you run "roslaunch livox_ros_driver livox_lidar_msg.launch" and "roslaunch xsens_mti_driver example.launch", both /livox/lidar and /imu/data topics are published, you can see data after "rostopic echo xxx". 
But after you run LI-Init, /livox/lidar disappears but /imu/data still works normally?

**Comment by zfc-zfc** [comment]
> Should i run livox_ros_driver to a terminal, xsens_mti_ros_driver to another terminal and lil_init to a third terminal

Yes you should run livox_ros_driver to a terminal, xsens_mti_ros_driver to another terminal and li_init to a third terminal.

**Comment by ManChrys** [comment]
> So you said, when you run "roslaunch livox_ros_driver livox_lidar_msg.launch" and "roslaunch xsens_mti_driver example.launch", both /livox/lidar and /imu/data topics are published, you can see data after "rostopic echo xxx". But after you run LI-Init, /livox/lidar disappears but /imu/data still works normally?

exactly!!





> Yes you should run livox_ros_driver to a terminal, xsens_mti_ros_driver to another terminal and li_init to a third terminal.
I tried it but when im launching lil_init, the terminal in which i am launching livox_ros_driver shut down and say something like that "livox ros driver stops because a same node is running" with red letters (i am not on my pc right now to send you the exactly message)

**Comment by zfc-zfc** [comment]
> unavailable

It's strange. Maybe you should check what is the name of the same node. As far as I know, LI-Init cannot have any conflicts with livox_ros_driver because we have tested it hundreds of times.

**Comment by ManChrys** [comment]
Yeah i know its really strange. Ill try it again tomorrow and if the promblem remain ill post here the screenshots.

Thanks for the fast response i really appreciate it.

**Comment by pingguofu** [comment]
Hello,
Has this problem been solved? I used the IMU of xsens and encountered the same problem.

**Comment by zfc-zfc** [comment]
> remains

How about try this: Only launch livox_ros_driver and IMU driver, record a bag and make sure this bag contain correct data (rosbag info xxx.bag). Then shut down the drivers, only run lidar_imu_init, then rosbag play xxx.bag.

**Comment by ManChrys** [comment]
Using your project you can calibrate LiDAR and imu in the beginning right ? If they are not synchronised how can I calibrate them using a bag file ?

**Comment by ManChrys** [comment]
> Hello,
> 
> Has this problem been solved? I used the IMU of xsens and encountered the same problem.
> 
> 
> 
> 

I'll be able to try it again in 2-3 hours from now . If I solve it I'll inform you .

**Comment by zfc-zfc** [comment]
> calibrate

Of course you can calibrate them using a bag file, otherwise why would I upload example bags?

**Comment by ManChrys** [comment]
> > calibrate
> 
> 
> 
> Of course you can calibrate them using a bag file, otherwise why would I upload example bags?

Yeah that's right . I'll try it in about 2-3 hours and I'll inform you 😃

**Comment by ManChrys** [comment]
Well i have to say the following things.

When im running  `roslaunch livox_ros_driver livox_lidar.launch` !!!alone!!! i have the following
![livox_ros_driver](https://user-images.githubusercontent.com/67521662/186837841-29042514-33f5-4f85-96e9-a1a850cb7bff.png)

When im running `roslaunch livox_ros_driver livox_lidar_msg.launch` !!!alone!!! i have the following
![livox_ros_msg](https://user-images.githubusercontent.com/67521662/186838044-3477425e-ba64-4451-8d50-9833a3875811.png)

When im running `roslaunch livox_ros_driver livox_lidar.launch` with `roslaunch lidar_imu_init livox_avia.launch` i have the following
![livoxdriver_lilinit](https://user-images.githubusercontent.com/67521662/186838318-d4c01fdb-8871-4064-b6aa-08c36b8e8208.png)

When im running `roslaunch xsens_mti_driver xsens_mti_node.launch` with `roslaunch lidar_imu_init livox_avia.launch` i have the following
![imudispley-liliinit](https://user-images.githubusercontent.com/67521662/186838426-d92af345-a50b-4786-9004-57497e7bb1f7.png)

Also i found that my imu even if is get recognized for some reason when im using `rostopic echo /imu/data` ii doesnt show me something. Using MT manager (imu's software) i have data.
![imu2](https://user-images.githubusercontent.com/67521662/186838718-af66b8f1-2b58-4074-bdba-cdc5abecddfe.png)

So im really confused :'D

**Comment by zfc-zfc** [comment]
> 

My bro, you should learn some basic knowledge about ROS (ros message and ros topic). Clearly, LI-Init wants to subscribe /livox/lidar with customized message format, while the livox_ros_driver you launched just publish /livox/lidar with pointcloud2 format. 
![image](https://user-images.githubusercontent.com/50921331/186839805-8b31c4c9-347b-4ae0-9f79-a95d993e92a6.png)

If you read the README of livox_ros_driver, you should notice there are two launch files given: 
![image](https://user-images.githubusercontent.com/50921331/186840185-be5a9c7e-342c-4f6c-a80f-f80e084f6f3c.png)

And in my previous answer, I have already said you should run **livox_lidar_msg.launch**.
![image](https://user-images.githubusercontent.com/50921331/186840339-1cc40b6d-1117-4100-a211-ccbe381bb6f3.png)

Maybe next time, you could firstly try to analyze the reason you failed by yourself. If the reason is truly caused by others not yourself, then ask others.

**Comment by ManChrys** [comment]
I fixed the problem with red letters

`[ERROR] [1661495465.896352538]: Client [/laserMapping] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.`

just change in livox_lidar.launch file the <arg name="xfer_format" default="0"/> to <arg name="xfer_format" default="1"/>

**Comment by ManChrys** [comment]
@zfc-zfc thank you for your time and help.

@pingguofu now it worked fine. imu model xsens mti - g - 710 gnss/ins

Ok the whole problem caused from the IMU driver and the custom pcb i have made to convert rs232 to ttl . I reinstall the imu drivers and i used a new pcb and everything is running smooth. 

![Screenshot from 2022-08-26 10-22-33](https://user-images.githubusercontent.com/67521662/186845971-40888a05-8b9f-4447-bd97-ae9836492f8c.png)
