### ISSUE TITLE
datatype/md5sum error

### ISSUE THREAD

**Issue by Congxilong** [hku-mars/LiDAR_IMU_Init#23]
[ERROR] [1661737358.718783357]: Client [/laserMapping] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.

When I finish compiling and running _Livox-mid360. launch_ and play my bag,the above error occurred.How to solve this problem?thanks!

**Comment by zfc-zfc** [comment]
> solve

It seems the /livox/lidar topic in your bag is pointcloud2 format. Please run **roslaunch livox_ros_driver livox_lidar_msg.launch** to get customized format. 
![image](https://user-images.githubusercontent.com/50921331/187134453-2216ad88-3635-472c-ae0f-f89a6f11ac96.png)

**Comment by Congxilong** [comment]
> > 解决
> 
> 似乎你包里的/livox/lidar主题是pointcloud2格式。请运行 **roslaunch livox_ros_driver livox_lidar_msg.launch** 以获取自定义格式。 ![图像](https://user-images.githubusercontent.com/50921331/187134453-2216ad88-3635-472c-ae0f-f89a6f11ac96.png)

Thanks,I solve my problem by this way,but the result is not satisfactory . I have tried both livox-mid360 and velodyne-VLP16 ,but after a while the map doesn't match . Do I need to modify cut_frame_num or  data_accum_length in YAML file ? Or what do I need to pay attention to when I record packets? Thanks for your time !

**Comment by zfc-zfc** [comment]
> 

Livox mid360 should be easy to succeed. It is recommended to give sufficient excitation following the .GIF in README.
![image](https://user-images.githubusercontent.com/50921331/187136678-e43f548f-6fba-4c38-ab55-782a2a0294b7.png)
