### ISSUE TITLE
How it work for rslidar16?

### ISSUE THREAD

**Issue by supertiechui** [hku-mars/LiDAR_IMU_Init#26]
报错如下：
Compute offset time using constant rotation model.
Compute offset time using constant rotation model.
[Initialization] Movement detected, data accumulation starts.

QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

[Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Data accumulation finished, Lidar IMU initialization begins.

============================================================ 

[laserMapping-1] process has died [pid 18438, exit code -11, cmd /home/yzw/catkin_li_calib/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1.log].
log file: /home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1*.log

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
我的是速腾16线的雷达，使用了rs_to_velodyne转成velodyne消息格式。但刚打开lidar和imu，各轴的旋转度就直接拉满了。请问这样应该怎么解决呢？

**Comment by zfc-zfc** [comment]
> 报错如下： Compute offset time using constant rotation model. Compute offset time using constant rotation model. [Initialization] Movement detected, data accumulation starts.
> 
> QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().)
> 
> [Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Data accumulation finished, Lidar IMU initialization begins.
> 
> ============================================================
> 
> [laserMapping-1] process has died [pid 18438, exit code -11, cmd /home/yzw/catkin_li_calib/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1.log]. log file: /home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1*.log
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> 我的是速腾16线的雷达，使用了rs_to_velodyne转成velodyne消息格式。但刚打开lidar和imu，各轴的旋转度就直接拉满了。请问这样应该怎么解决呢？

请问雷达里程计是否正常运行？rviz中的点云地图是否清晰一致？

**Comment by shaoqinshi** [comment]
只有初始化的过程，初始化之后直接失败了。rviz中的点云也乱跑了

**Comment by zfc-zfc** [comment]
> 只有初始化的过程，初始化之后直接失败了。rviz中的点云也乱跑了

请问在收集数据过程中（进度条未达到100%前），点云地图是否正常？在保证点云不糊的情况下，尽量多给一点旋转，给予充分的激励。

**Comment by af-doom** [comment]
> 报错如下： Compute offset time using constant rotation model. Compute offset time using constant rotation model. [Initialization] Movement detected, data accumulation starts.
> 
> QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().)
> 
> [Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Data accumulation finished, Lidar IMU initialization begins.
> 
> ============================================================
> 
> [laserMapping-1] process has died [pid 18438, exit code -11, cmd /home/yzw/catkin_li_calib/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1.log]. log file: /home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1*.log
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> 我的是速腾16线的雷达，使用了rs_to_velodyne转成velodyne消息格式。但刚打开lidar和imu，各轴的旋转度就直接拉满了。

> > 报错如下： Compute offset time using constant rotation model. Compute offset time using constant rotation model. [Initialization] Movement detected, data accumulation starts.
> > QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().)
> > [Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||] [Initialization] Data accumulation finished, Lidar IMU initialization begins.
> > ============================================================
> > [laserMapping-1] process has died [pid 18438, exit code -11, cmd /home/yzw/catkin_li_calib/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1.log]. log file: /home/yzw/.ros/log/16d18caa-2f4a-11ed-adb7-5405db29cc01/laserMapping-1*.log
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> > 
> > 
> > 我的是速腾16线的雷达，使用了rs_to_velodyne转成velodyne消息格式。但刚打开lidar和imu，各轴的旋转度就直接拉满了。请问这样应该怎么解决呢？
> 
> 请问雷达里程计是否正常运行？rviz中的点云地图是否清晰一致？

您好。你成功标定velodyne16了吗？
