### ISSUE TITLE
Can't catkin_make - Missing States.h

### ISSUE THREAD

**Issue by protoCAD** [hku-mars/LiDAR_IMU_Init#27]
![catkin_make-error](https://user-images.githubusercontent.com/92993769/189478532-7c88fb58-28d0-44f4-b5ba-e2c0befd9429.JPG)

Seems this file has been removed?

**Comment by zfc-zfc** [comment]
> ![catkin_make-error](https://user-images.githubusercontent.com/92993769/189478532-7c88fb58-28d0-44f4-b5ba-e2c0befd9429.JPG)
> 
> Seems this file has been removed?

For the first make, use "catkin_make -j"
