### ISSUE TITLE
Fails build

### ISSUE THREAD

**Issue by rlabs-oss** [hku-mars/LiDAR_IMU_Init#28]
...src/LiDAR_IMU_Init/src/laserMapping.cpp:1278:1: error: expected ‘}’ at end of input
 1278 | }
      | ^
...src/LiDAR_IMU_Init/src/laserMapping.cpp:772:33: note: to match this ‘{’

**Comment by jin-bae-joulea** [comment]
I'm sorry, how did you fix this?
