### ISSUE TITLE
有关mid-70的配置文件的问题。

### ISSUE THREAD

**Issue by hr2894235132** [hku-mars/LiDAR_IMU_Init#32]
您好，请问一下，对于livox mid-70，怎么确定.yaml文件中的以下参数：
`lidar_type: 1               # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 2`
如能抽空帮我解答一下，万分感谢！！！！

**Comment by zfc-zfc** [comment]
> 您好，请问一下，对于livox mid-70，怎么确定.yaml文件中的以下参数： `lidar_type: 1 # Livox series LiDAR feature_extract_en: false scan_line: 6 blind: 2` 如能抽空帮我解答一下，万分感谢！！！！

lidar_type: 1 #对于所有的LIVOX LiDAR，我们推荐使用livox_ros_driver提供的自定义数据类型，即[CustomMsg](https://github.com/Livox-SDK/livox_ros_driver/tree/master/livox_ros_driver/msg)
feature_extract_en: false #绝大部分情况下推荐false，定位会更鲁棒
scan_line: 启动mid70，运行livox_ros_driver，等待其成功发布 /livox/lidar后，用rostopic echo /livox/lidar 查看最大的line值，则scan_line就应该填 最大的line值+1. 如livox avia最大的line值是5，则填6.
blind: 雷达的盲区，查阅手册可获得

**Comment by hr2894235132** [comment]
> 

您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70
![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)

**Comment by zfc-zfc** [comment]
> > 
> 
> 您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70 ![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)

那config文件里 scan_line填1即可

**Comment by hr2894235132** [comment]
> > > 
> > 
> > 
> > 您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70 ![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)
> 
> 那config文件里 scan_line填1即可

好的，非常感谢

**Comment by hr2894235132** [comment]
> > > > 
> > > 
> > > 
> > > 您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70 ![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)
> > 
> > 
> > 那config文件里 scan_line填1即可
> 
> 好的，非常感谢
您好，还想麻烦问一下，blind值比如等于2是代表什么呢？
手册上是这样的：
![Screenshot from 2022-10-12 16-31-45](https://user-images.githubusercontent.com/86639226/195292552-97dd1a7f-6690-4fb3-a59b-a5d302520ea6.png)
是不是blind值就是5呢？

**Comment by zfc-zfc** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70 ![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)
> > > 
> > > 
> > > 那config文件里 scan_line填1即可
> > 
> > 
> > 好的，非常感谢
> > 您好，还想麻烦问一下，blind值比如等于2是代表什么呢？
> > 手册上是这样的：
> > ![Screenshot from 2022-10-12 16-31-45](https://user-images.githubusercontent.com/86639226/195292552-97dd1a7f-6690-4fb3-a59b-a5d302520ea6.png)
> > 是不是blind值就是5呢？

盲区的单位是m, 所以应该填0.05.

**Comment by hr2894235132** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 您好，我用rostopic echo /livox/lidar 查看我的line值，但是显示的信息都为0,这是正常的么？我是livox mid70 ![Screenshot from 2022-10-12 15-42-46](https://user-images.githubusercontent.com/86639226/195281952-60060c72-0702-4437-b298-0db1fc3b0995.png)
> > > > 
> > > > 
> > > > 那config文件里 scan_line填1即可
> > > 
> > > 
> > > 好的，非常感谢
> > > 您好，还想麻烦问一下，blind值比如等于2是代表什么呢？
> > > 手册上是这样的：
> > > ![Screenshot from 2022-10-12 16-31-45](https://user-images.githubusercontent.com/86639226/195292552-97dd1a7f-6690-4fb3-a59b-a5d302520ea6.png)
> > > 是不是blind值就是5呢？
> 
> 盲区的单位是m, 所以应该填0.05.

好的，非常感谢！！！

**Comment by ZhouBin818** [comment]
请问可以分享一下你的MID70配置文件吗。。。万分感谢

**Comment by hr2894235132** [comment]
> 请问可以分享一下你的MID70配置文件吗。。。万分感谢

我主要修改的就是上面问到的参数，其他对着mid-70的手册修改成相应的就没什么了。
