### ISSUE TITLE
In LI_init.cpp line 533

### ISSUE THREAD

**Issue by MRgsj** [hku-mars/LiDAR_IMU_Init#34]
请问关于Rot_percent这个变量的确定，它的数学依据是什么，为什么每个方向上要选择另外两个方向上的特征值相乘。
看代码的时候不太明白，感谢作者。
V3D Rot_percent(Scaled_Eigen[1] * Scaled_Eigen[2],
                        Scaled_Eigen[0] * Scaled_Eigen[2],
                        Scaled_Eigen[0] * Scaled_Eigen[1]);

**Comment by zfc-zfc** [comment]
> 请问关于Rot_percent这个变量的确定，它的数学依据是什么，为什么每个方向上要选择另外两个方向上的特征值相乘。 看代码的时候不太明白，感谢作者。 V3D Rot_percent(Scaled_Eigen[1] * Scaled_Eigen[2], Scaled_Eigen[0] * Scaled_Eigen[2], Scaled_Eigen[0] * Scaled_Eigen[1]);

这是一个启发式的，用于衡量外参的能观性，从而对应于激励程度，大概推导如下：
![image](https://user-images.githubusercontent.com/50921331/196025264-282f7fce-da92-46cb-a65f-fbce3eae4925.png)
