### ISSUE TITLE
Hello, I have the following problems when calibrating xsens and velodyne16

### ISSUE THREAD

**Issue by af-doom** [hku-mars/LiDAR_IMU_Init#35]
![2022-10-15 21-17-31 的屏幕截图](https://user-images.githubusercontent.com/91470350/195989905-6bc0d828-5d34-401e-8505-ca93091343bb.png)
The specific model is xsens MTI300 \ velodyne 16; I'm very interested in this project.Thanks again,

**Comment by af-doom** [comment]
Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2

**Comment by zfc-zfc** [comment]
> Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2

Hi, are you convenient to share the bag that the error occurred?

**Comment by af-doom** [comment]
> > Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2
> 
> Hi, are you convenient to share the bag that the error occurred?

Hello, thank you very much for your reply.  The bag has been sent to your mailbox.  Thank you very much.

**Comment by zfc-zfc** [comment]
> > > Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2
> > 
> > 
> > Hi, are you convenient to share the bag that the error occurred?
> 
> Hello, thank you very much for your reply. The bag has been sent to your mailbox. Thank you very much.

Hi, I didn't receive the email. How about sending it to zhufc@connect.hku.hk again, or upload your bag to onedrive and share a link?

**Comment by af-doom** [comment]
> > > > Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2
> > > 
> > > 
> > > Hi, are you convenient to share the bag that the error occurred?
> > 
> > 
> > Hello, thank you very much for your reply. The bag has been sent to your mailbox. Thank you very much.
> 
> Hi, I didn't receive the email. How about sending it to [zhufc@connect.hku.hk](mailto:zhufc@connect.hku.hk) again, or upload your bag to onedrive and share a link?

Thank you very much. I have installed your email address and resend it

**Comment by af-doom** [comment]
Thank you very much. I wish I were next to the computer now. I'll see it soon. Could you tell me what the problem is



---Original---
From: "Fangcheng ***@***.***&gt;
Date: Tue, Oct 18, 2022 18:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hku-mars/LiDAR_IMU_Init] Hello, I have the following problemswhen calibrating xsens and velodyne16 (Issue #35)




      
Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2
  
Hi, are you convenient to share the bag that the error occurred?
  
Hello, thank you very much for your reply. The bag has been sent to your mailbox. Thank you very much.
  
Hi, I didn't receive the email. How about sending it to ***@***.*** again, or upload your bag to onedrive and share a link?
  
Thank you very much. I have installed your email address and resend it
 The bug is fixed. Please try the newest version. Thanks.

**Comment by zfc-zfc** [comment]
> Thank you very much. I wish I were next to the computer now. I'll see it soon. Could you tell me what the problem is
> […](#)
> ---Original--- From: "Fangcheng ***@***.***&gt; Date: Tue, Oct 18, 2022 18:34 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [hku-mars/LiDAR_IMU_Init] Hello, I have the following problemswhen calibrating xsens and velodyne16 (Issue #35) Hello, I still haven't solved this problem. There is no such error when the data package runs Fast-LIO2 Hi, are you convenient to share the bag that the error occurred? Hello, thank you very much for your reply. The bag has been sent to your mailbox. Thank you very much. Hi, I didn't receive the email. How about sending it to ***@***.*** again, or upload your bag to onedrive and share a link? Thank you very much. I have installed your email address and resend it The bug is fixed. Please try the newest version. Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Some points of Velodyne16 are invalid, the coordinate value is nan. These points should be discarded but I ignored this thing before. The new version is tested OK now.

**Comment by af-doom** [comment]
OK, thank you very much for your answer



---Original---
From: "Fangcheng ***@***.***&gt;
Date: Tue, Oct 18, 2022 20:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hku-mars/LiDAR_IMU_Init] Hello, I have the following problemswhen calibrating xsens and velodyne16 (Issue #35)

**Comment by HamzaCetin0** [comment]
Hi @af-doom. How did you solve the problem. I have the same IMu and Lidar. I encountered the same issue. After the initialization starts the laser scan drifts and then it gives the same error like you got. Can you help me please?
