### ISSUE TITLE
如何判断结果的好坏？

### ISSUE THREAD

**Issue by hr2894235132** [hku-mars/LiDAR_IMU_Init#36]
您好，感谢您的工作给我雷达和imu的标定工作带来了便捷，我想请问一下，得到标定后的结果，我怎么去判断标定的精度呢，尤其是旋转的精度好坏。

**Comment by zfc-zfc** [comment]
> 您好，感谢您的工作给我雷达和imu的标定工作带来了便捷，我想请问一下，得到标定后的结果，我怎么去判断标定的精度呢，尤其是旋转的精度好坏。

如果你的雷达和IMU是在CAD模型上安装，可以和图纸的参考值对比。如果是随意安装的，可以跑一个FAST-LIO2看看能否正常运行，会不会漂，从而判断是否得到了有效的标定。

**Comment by hr2894235132** [comment]
> > 您好，感谢您的工作给我雷达和imu的标定工作带来了便捷，我想请问一下，得到标定后的结果，我怎么去判断标定的精度呢，尤其是旋转的精度好坏。
> 
> 如果你的雷达和IMU是在CAD模型上安装，可以和图纸的参考值对比。如果是随意安装的，可以跑一个FAST-LIO2看看能否正常运行，会不会漂，从而判断是否得到了有效的标定。

谢谢您的耐心回复，现在已经测试成功fast-lio2了，非常优秀的工作！
