### ISSUE TITLE
Avia lidar ,Data accumulation finished, but ”Max Cross-correlation: IMU lag wtr Lidar : 47 corrupted size vs. prev_size [laserMapping-1] process has died“

### ISSUE THREAD

**Issue by skyengine83** [hku-mars/LiDAR_IMU_Init#38]
I use avia lidar , but dose not get initialization result .
[263d2f690ff238d39ef8f3b4ecbbf8c](https://user-images.githubusercontent.com/13100641/198927551-bfe14bf9-95df-4586-b4e8-4ba6588829e5.png)

```
[Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Data accumulation finished, Lidar IMU initialization begins.

============================================================ 

Max Cross-correlation: IMU lag wtr Lidar : 47
corrupted size vs. prev_size
[laserMapping-1] process has died [pid 16581, exit code -6, cmd /mnt/hgfs/Share/20.lidar_imu_calib/03.hku/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/home/fcy/.ros/log/f030c314-55bd-11ed-98c1-000c29a5b58f/laserMapping-1.log].
log file: /home/fcy/.ros/log/f030c314-55bd-11ed-98c1-000c29a5b58f/laserMapping-1*.log
^C[rviz-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by skyengine83** [comment]
Lidar IMU initialization begins but doesn't finished.

**Comment by xaioqi** [comment]
Hello, I also encountered the same problem, how did you solve it? ? Thanks

**Comment by nes9966** [comment]
Did you ever solve this issue?

**Comment by seungjae99** [comment]
@zfc-zfc 
Hi, thanks for sharing your great work, but I'm also facing the same issue as mentioned above. Could you please provide a solution?

[Initialization] Rotation around Lidar X Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Y Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Rotation around Lidar Z Axis: 100% [||||||||||||||||||||||||||||||]
[Initialization] Data accumulation finished, Lidar IMU initialization begins.

============================================================ 

Max Cross-correlation: IMU lag wtr Lidar : -778
[laserMapping-1] process has died [pid 20464, exit code -11, cmd /home/catkin_ws/devel/lib/lidar_imu_init/li_init __name:=laserMapping __log:=/root/.ros/log/ce6da3c6-5b12-11ef-8d79-dcfe07109cf5/laserMapping-1.log].
log file: /root/.ros/log/ce6da3c6-5b12-11ef-8d79-dcfe07109cf5/laserMapping-1*.log
^C[rviz-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done


if you need my bag file i can share it with you

thanks
