### ISSUE TITLE
Question about Extrinsic Translation algorithm.

### ISSUE THREAD

**Issue by Taeyoung96** [hku-mars/LiDAR_IMU_Init#41]
@zfc-zfc   
Thanks for your great work.  
I have a question because the code is different from equation (23) in the paper.  

The equation (23) shown in the paper is as follows.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/200166404-01c2afde-7133-48ed-b9bc-7c7362b90009.png" width = "500" ></p>  

And I understood the code that implemented this as `LI_Init::solve_trans_biasacc_grav()`.  
Looking at the residual function `Linear_acc_Cost`, I find that the variable `R_LL0_T`(the estimated attitude (rotation matrix) at the end lidar point), which is not mentioned in the paper, continues to be used.  
```
Eigen::Matrix<T, 3, 1> resi = R_LL0_T * R_LI_T_transpose * IMU_linear_acc_T - R_LL0_T * bias_aL
                                      + R_GL0 * STD_GRAV - Lidar_linear_acc_T - R_LL0_T * Jacob_trans_T * T_IL;
```

Why does this variable continue to be used?  
I'd appreciate it if you could give me an answer.

**Comment by zfc-zfc** [comment]
> 

Please refer to Equation (22)

> bias_aL

![image](https://user-images.githubusercontent.com/50921331/200233962-fb89e60f-231c-42ec-8a9f-dff635b36acb.png)

**Comment by Taeyoung96** [comment]
@zfc-zfc   
Thank you for your quick response. :+1:
