### ISSUE TITLE
robosense数据集

### ISSUE THREAD

**Issue by tuzhiming2016** [hku-mars/LiDAR_IMU_Init#45]
请问可以提供一个速腾雷达的数据集吗

**Comment by Fellowflyingsky** [comment]
作者你好：
我测试  robosense helios32线和向量科技6轴imu 经常遇到后端热refinement出现 雷达里程计飘逸现象。请问这是为啥？ 
![1](https://user-images.githubusercontent.com/71952790/205897264-5aab4b10-a3a1-49b0-abad-475edf697d3a.png)
![2](https://user-images.githubusercontent.com/71952790/205897367-b52186af-17dd-408b-85b2-8c9e76184e72.png)

**Comment by Fellowflyingsky** [comment]
@XW-HKU

**Comment by huangwefeng121** [comment]
> 作者你好： 我测试 robosense helios32线和向量科技6轴imu 经常遇到后端热refinement出现 雷达里程计飘逸现象。请问这是为啥？

你好，我也用速腾雷达出现了这个imu漂移严重的问题，请问你是怎么解决的
