### ISSUE TITLE
关于镭神C16雷达和IMU的标定问题

### ISSUE THREAD

**Issue by PigletPh** [hku-mars/LiDAR_IMU_Init#52]
大佬，请问我在镭神雷达与IMU标定时，出现Failed to find match for field 'time'. 同时出现Compute offset time using constant rotation model问题，请问怎么回事，谢谢

**Comment by zfc-zfc** [comment]
> time

LI-Init需要准确地指导每一个点的时间戳，通常其他雷达每个点的时间戳都保存在"time" 或“timestamp” 或 “t” 这些filed里，你可以确认一下你的雷达发出的点云是否有这些field.

**Comment by PigletPh** [comment]
@zfc-zfc 您好，我的雷达发布数据格式如下：
![image](https://user-images.githubusercontent.com/44089510/228788674-5af8bb2d-8752-4a0b-9d21-b7ec6ff61a6c.png)
我对比了下LiDAR_IMU_Init中velodyne雷达定义格式，发现是一样的，但我将time的类型从double转为float，编译没有错但是雷达数据无法导入到，请问怎么回事，万分感谢

**Comment by zfc-zfc** [comment]
> float

你需要确认一下原始点云的time是什么类型，如果是double那么代码也应该为double，若是float同理；总之要保持一致才能读到。

**Comment by kkaerma** [comment]
您好请问您雷神c16改好了吗，能不能提供一下源代码，谢谢
