### ISSUE TITLE
时间偏移实验

### ISSUE THREAD

**Issue by gongjun136** [hku-mars/LiDAR_IMU_Init#53]
我复现了一下时间偏移的实验，对每个订阅的imu做了0.25s的偏移，虽然时间偏移回来了，但是旋转外参仿佛变大了许多。我使用的livox horizon激光雷达
[Final Result] Rotation LiDAR to IMU    = -0.981229 -0.377143 -0.491367 deg
[Final Result] Translation LiDAR to IMU =  0.017507 -0.007343  0.015338 m
[Final Result] Time Lag IMU to LiDAR    = -0.00506889 s 
[Final Result] Bias of Gyroscope        = -0.001044  0.000209 -0.001608 rad/s
[Final Result] Bias of Accelerometer    =  0.020279 -0.007703 -0.039088 m/s^2
[Final Result] Gravity in World Frame   =  0.449729  0.477563 -9.780474 m/s^2
![image](https://user-images.githubusercontent.com/73570451/224059070-dfe77695-73bf-48c8-928b-a28f4201ebf7.png)

**Comment by Nothand0212** [comment]
您好，这个Time Lag IMU to LiDAR是指什么值？假如IMU和雷达的ROS时间戳都是10，那么实际上10时刻的雷达数据，对应的应该是10-0.25=9.75时刻的IMU数据？
