### ISSUE TITLE
mid360 calibration issues

### ISSUE THREAD

**Issue by fratopa** [hku-mars/LiDAR_IMU_Init#56]
Hi! thank you for the great too, I was trying to calibrate my lidar but the process crashes every time after reaching the refinement phase. I have checked most of the issues in the repo of people having the same problem but none of their solutions work for me. 

If anyone wants to have a look at the bag I am using the link is down there, the data are coming from a simulated mid360 
https://drive.google.com/drive/folders/1rh2lxiU4WobuZNalZyjFguW-seLbXZ-E?usp=share_link

**Comment by zfc-zfc** [comment]
> Hi! thank you for the great too, I was trying to calibrate my lidar but the process crashes every time after reaching the refinement phase. I have checked most of the issues in the repo of people having the same problem but none of their solutions work for me.
> 
> If anyone wants to have a look at the bag I am using the link is down there, the data are coming from a simulated mid360 https://drive.google.com/drive/folders/1rh2lxiU4WobuZNalZyjFguW-seLbXZ-E?usp=share_link

Could you please share the bag to zhufc@connect.hku.hk ? Thank you.

**Comment by fratopa** [comment]
> > Hi! thank you for the great too, I was trying to calibrate my lidar but the process crashes every time after reaching the refinement phase. I have checked most of the issues in the repo of people having the same problem but none of their solutions work for me.
> > If anyone wants to have a look at the bag I am using the link is down there, the data are coming from a simulated mid360 https://drive.google.com/drive/folders/1rh2lxiU4WobuZNalZyjFguW-seLbXZ-E?usp=share_link
> 
> Could you please share the bag to [zhufc@connect.hku.hk](mailto:zhufc@connect.hku.hk) ? Thank you.

I just gave you access to the folder, let me know if it is ok :)

**Comment by zfc-zfc** [comment]
> 
![image](https://user-images.githubusercontent.com/50921331/226883500-4135f903-88c9-4dd4-a44a-a10663a3feaf.png)

In your bag the offset_time of each point is incorrect. The lidar frequency is 10Hz, the maximum offset time should be around 1e8 us, while when I print the offset_time in your bag, the maximum value is only around 5000000 us.

**Comment by fratopa** [comment]
![better](https://user-images.githubusercontent.com/66642543/226892653-4b28e5d4-b1ea-4bb0-aea7-d31be6669387.png)
I increased the offset time and the results are much improved. May I ask why it is such a crucial parameter?

**Comment by zfc-zfc** [comment]
> parameter

This parameter is used for motion compensation (point undistortion).

**Comment by fratopa** [comment]
Oh I see, I guess this is also why it expects the points in the custom livox format. The regular poincloud2 message doesn't have that information. I wonder if there is a way to have the algorithm work with regular pointcloud2 messages at the cost of the deskewing step. Maybe that's a question better left to another issue. 
In the meantime, thank you very much for your help!

**Comment by af-doom** [comment]
> ![better](https://user-images.githubusercontent.com/66642543/226892653-4b28e5d4-b1ea-4bb0-aea7-d31be6669387.png) I increased the offset time and the results are much improved. May I ask why it is such a crucial parameter?

The 360 data format I recorded is pointcloud2. How should I complete the calibration

**Comment by fratopa** [comment]
> > ![better](https://user-images.githubusercontent.com/66642543/226892653-4b28e5d4-b1ea-4bb0-aea7-d31be6669387.png) I increased the offset time and the results are much improved. May I ask why it is such a crucial parameter?
> 
> The 360 data format I recorded is pointcloud2. How should I complete the calibration

The newest version of the driver added timestamps for the timestamps in pointcloud2. Try installing the new version and rerecord your data, to the best of my knowledge, you can't add them after the fact
