### ISSUE TITLE
Failed to calibrate using the sample data Hesai_library.bag

### ISSUE THREAD

**Issue by CharlieV5** [hku-mars/LiDAR_IMU_Init#66]
I download the sample data here: [Lidar IMU Initialization Datasets](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/zhufc_connect_hku_hk/EgdJ_F763sVOnkUNBRv-op8BmNL7eZrxETu2zSEAoiRX4A?e=cbNiJI).
I have test the Hesai_library.bag and Hesai_apartment1.bag. The Initialization has never reach 100% when the rosbag play ends, as the screen shot below.
Are there any mistakes with the data or the settings?

![2023-05-07 21-00-26屏幕截图](https://user-images.githubusercontent.com/8245892/236679577-abe9334a-4dea-418d-9341-7f9eeda4dd5e.png)

![2023-05-07 21-01-27屏幕截图](https://user-images.githubusercontent.com/8245892/236679618-7fdb1103-c2ac-4093-9d66-a38784918b53.png)

**Comment by zfc-zfc** [comment]
Adjusting data_accum_length and cut_frame_num would fix this, please try setting data_accum_length to 300 and cut_frame_num to 4.

**Comment by CharlieV5** [comment]
> Adjusting data_accum_length and cut_frame_num would fix this, please try setting data_accum_length to 300 and cut_frame_num to 4.

Thank you!
