### ISSUE TITLE
测试效果不太良好

### ISSUE THREAD

**Issue by SlamSmallFish** [hku-mars/LiDAR_IMU_Init#70]
作者，您好！向您请教一个问题，我在测试您提供的mid360的数据的时候，一运行到 refinement 时数据就开始跑偏了，而且得到的外参不如初始化时准确，这是为什么呢？

**Comment by SlamSmallFish** [comment]
![123](https://github.com/hku-mars/LiDAR_IMU_Init/assets/126395838/917c4d07-b9db-47ab-826d-3337bdd16c6b)
![123](https://github.com/hku-mars/LiDAR_IMU_Init/assets/126395838/fa287f0d-500b-46b9-9317-a98637021e9b)

**Comment by zfc-zfc** [comment]
> 作者，您好！向您请教一个问题，我在测试您提供的mid360的数据的时候，一运行到 refinement 时数据就开始跑偏了，而且得到的外参不如初始化时准确，这是为什么呢？

你的参数是怎么样的呢？可以截一张yaml文件的图吗

**Comment by CharlieV5** [comment]
与[SlamSmallFish]的问题一样，XYZ三轴激励时地图正常，到online refinement轨迹和地图就飘了
经过研究yaml参数，发现要把mean_acc_norm设置为1（一开始设置的是9.805），表示livox内部自带的IMU
如图，供参考！

![无标题](https://github.com/hku-mars/LiDAR_IMU_Init/assets/8245892/650e94f6-d824-42ad-b584-54f4e64c7364)
![refine-结果](https://github.com/hku-mars/LiDAR_IMU_Init/assets/8245892/6f284f8a-174f-46ea-8126-137b3d530044)


> SlamSmallFish

**Comment by zfc-zfc** [comment]
> 与[SlamSmallFish]的问题一样，XYZ三轴激励时地图正常，到online refinement轨迹和地图就飘了 经过研究yaml参数，发现要把mean_acc_norm设置为1（一开始设置的是9.805），表示livox内部自带的IMU 如图，供参考！
> 
> ![无标题](https://user-images.githubusercontent.com/8245892/253636053-650e94f6-d824-42ad-b584-54f4e64c7364.png) ![refine-结果](https://user-images.githubusercontent.com/8245892/253636437-12adbb28-afd6-46f6-a5d0-59f6b4de0b23.png)
> 
> > SlamSmallFish

是的，我在README里面写的很清楚，Livox内置IMU需要填 1
