### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by 5204338** [hku-mars/LiDAR_IMU_Init#72]
aserMapping.cpp:951:37: error: ‘omp_fout_out’ was not declared in this scope; did you mean ‘fout_out’?
  951 |     double t_update_start = omp_fout_out.close();
laserMapping.cpp:974:5: error: ‘get_wtime’ was not declared in this scope; did you mean ‘getitimer’?
  974 |     get_wtime();
大佬有空帮忙解决一下，我C++比较差

**Comment by 5204338** [comment]
大佬你是不是最近修改了什么代码，导致源码有问题了

**Comment by zfc-zfc** [comment]
> omp_fout_out
你的报错里提到的“omp_fout_out”和“get_wtime”，在这个仓库里的laserMapping.cpp都不存在。你是不是编译错代码了，编译的FAST-LIO？

**Comment by 5204338** [comment]
是的，后面我自己发现问题了，电脑很卡，导致我之前没出错的代码出问题了，然后让我感觉问题出在新的代码里，自己比较粗心，没仔细看报错来者，谢谢您

**Comment by 5204338** [comment]
问题已解决
