### ISSUE TITLE
为什么室内工厂建图的出发点和停止点对应不上

### ISSUE THREAD

**Issue by 5204338** [hku-mars/LiDAR_IMU_Init#74]
建图的起点和终点在现实中是同一个点，但是在地图中生成的起点和终点对应不上，这是为什么呢？

**Comment by 5204338** [comment]
这张图是我的建图效果，另外rosbag的包您需要，我也可以给你
![2](https://github.com/hku-mars/LiDAR_IMU_Init/assets/93042446/0e697d74-7d51-45de-bbcc-60f14e3822a7)

**Comment by zfc-zfc** [comment]
> 这张图是我的建图效果，另外rosbag的包您需要，我也可以给你 ![2](https://user-images.githubusercontent.com/93042446/256171313-0e697d74-7d51-45de-bbcc-60f14e3822a7.png)

看起来是雷达在长走廊里退化了，这种情况绝大多数雷达SLAM算法都很难handle，和标定没啥关系。

**Comment by 5204338** [comment]
好的，谢谢您

**Comment by 5204338** [comment]
> 雷达在长走廊里退化了，这种情况绝大多数雷达SLAM算法都很难handle

好的，谢谢您。
