### ISSUE TITLE
雷达和IMU位姿关系不变，两次录制的不同rosbag包，标定产生的结果偏差很大，这是正确在容许范围内吗

### ISSUE THREAD

**Issue by 5204338** [hku-mars/LiDAR_IMU_Init#78]
尊敬的港大团队您好，我有个问题，想问一下，在雷达和IMU位姿关系不变的前提下，两次录制的不同rosbag包，标定产生的外参结果偏差达到厘米级，这是允许的，正确的吗？
![3](https://github.com/hku-mars/LiDAR_IMU_Init/assets/93042446/1d9e9e34-4a58-4a1d-898c-57882838360b)

**Comment by goldtimes** [comment]
很明显第二次的建图感觉是漂了,需要查看rviz中的里程计是否漂移
