### ISSUE TITLE
time lag lidar-imu

### ISSUE THREAD

**Issue by ManChrys** [hku-mars/LiDAR_IMU_Init#83]
hello i would like to ask whats the ideal time difference between lidar and imu for mapping (that means the best precision)? under second ? some miliseconds? for example i have 80 miliseconds. Is this diff big ?

Thanks in advance.

**Comment by zfc-zfc** [comment]
> hello i would like to ask whats the ideal time difference between lidar and imu for mapping (that means the best precision)? under second ? some miliseconds? for example i have 80 miliseconds. Is this diff big ?
> 
> Thanks in advance.

Based on experience, the smaller the time difference, the higher the accuracy. 80 milliseconds is a relatively large time difference and can cause significant issues during high-speed motion. Typically, a time difference of within 5 milliseconds can generally meet most requirements.

**Comment by ManChrys** [comment]
Thanks my friend !!
