### ISSUE TITLE
运行自己的数据集，出现运行错误，能否帮忙跑一下我这个数据集？

### ISSUE THREAD

**Issue by rainlord2** [hku-mars/LiDAR_IMU_Init#97]
您好，
         下面是我的数据集，我在标定的时候，出现各种运行错误，程序会崩溃，能否帮忙跑一下我这个数据集，看看哪里有问题，麻烦了，多谢！
    采用外置imu，雷达是avia。
    lid_topic:  "/livox/lidar"
    imu_topic:  "/IMU_data"
百度云：
链接：https://pan.baidu.com/s/1RfyiaDvajAS1T4byoi1HFg 
提取码：fdj8

**Comment by 85256638** [comment]
麻烦以后大佬close问题之前，如果问题解决了的话，请把解决方法发一下。这样帮助后人。
